[pytest]
testpaths = tests deploy/aws/tests
filterwarnings =
    ignore:cannot collect test class 'TestRecord':pytest.PytestCollectionWarning
    ignore:datetime.datetime.utcnow\(\) is deprecated:DeprecationWarning:botocore.*
